data:
  path: "${projectDir}/data"
  out: "${projectDir}/data"
  reads: "reads"
  glob: "*R{1,2}*.fastq.gz"
  adapters: "adapters.fasta"
  time: "${projectDir}/data/time"

fastp:
  quality: "20"
  autodetect: "True"

process:
  executor: "local"

time:
  bin: "/usr/bin/time"
  flags: "-v"

container:
  bin: "apptainer"
  opts: ""
  exec: "exec"
  exec_opts: ""
  monolithic: "True"
  path: "${projectDir}/containers/comboseq.sif"

fastqc:

fastp:
  cores: "8"
  memory: "60G"
  container: "True"
  path: "${projectDir}/containers/comboseq.sif"
  bin: "fastp"

template:
  cores: "1"
  memory: "1G"
  time: "1.hour"
  queue: "work"

