process:
  executor: "local"

time:
  bin: "/usr/bin/time"
  flags: "-v"

container:
  bin: "apptainer"
  opts: ""
  exec: "exec"
  exec_opts: ""
  monolithic: "True"
  path: "${projectDir}/containers/comboseq.sif"

fastqc:

fastp:
  cores: "8"
  memory: "60G"
  container: "True"
  path: "${projectDir}/containers/comboseq.sif"
  bin: "fastp"
  quality: "20"
  autodetect: "True"

template:
  cores: "1"
  memory: "1G"
  time: "1.hour"
  queue: "work"

