process:
  executor: "local"

time:
  bin: "/usr/bin/time"
  flags: "-v"

parallel:
  bin: "parallel"
  flags: ""

container:
  bin: "apptainer"
  opts: ""
  exec: "exec"
  exec_opts: ""
  monolithic: "True"
  path: "${projectDir}/containers/comboseq.sif"

extract:
  cores: "8"
  memory: "8G"
  container: "False"
  bin: "gunzip"

fastqc:

fastp:
  cores: "8"
  memory: "60G"
  container: "True"
  path: "${projectDir}/containers/comboseq.sif"
  bin: "fastp"
  quality: "20"
  autodetect: "True"

data:
  path: "${projectDir}/data"
  out: "${projectDir}/data"
  reads: "reads"
  glob: "*R{1,2}*.fastq.gz"
  adapters: "adapters.fasta"
  time: "time"

