process:
  executor: "local"

time:
  bin: "/usr/bin/time"
  flags: "-v"

parallel:
  bin: "parallel"
  flags: ""

container:
  bin: "apptainer"
  opts: ""
  exec: "exec"
  exec_opts: ""
  monolithic: "False"
  path: "${projectDir}/containers/comboseq"

tools:
  bc: "bc"
  wc: "wc"

extract:
  process: "local"
  cores: "8"
  memory: "8"
  container: "False"
  bin: "pigz"
  flags: ""

samtools:
  cores: "4"
  memory: "8"
  container: "True"
  direct: "False"
  path: ""
  bin: "fastp"
  flags: ""

fastp:
  cores: "4"
  memory: "-1"
  buffer: "4"
  container: "False"
  direct: "False"
  path: "${projectDir}/containers/comboseq.sif"
  bin: "fastp"
  flags: ""
  quality: "20"
  trimf: "10"
  trimt: "0"
  autodetect: "False"
  compress: "True"
  compress_level: "5"

star:
  cores: "32"
  memory: "48"
  container: "True"
  path: "${projectDir}/containers/comboseq.sif"
  bin: "STAR"
  flags: ""

trinity:
  cores: "16"
  memory: "48"
  container: "True"
  path: "${projectDir}/containers/trinity.sif"
  bin: "Trinity"
  flags: ""

fastqc:
  cores: "1"
  memory: "-1"
  container: "False"
  direct: "False"
  path: "${projectDir/containers/comboseq.sif}"
  bin: "fastqc"
  flags: ""

multiqc:
  cores: "1"
  memory: "1"
  container: "True"
  direct: "False"
  path: "${projectDir/containers/comboseq.sif}"
  bin: "multiqc"
  flags: ""

seqkit:
  cores: "1"
  memory: "1"
  container: "True"
  direct: "False"
  path: "${projectDir/containers/comboseq.sif}"
  bin: "seqkit"
  flags: ""

data:
  path: "${projectDir}/data"
  out: "${projectDir}/data"
  reports: "${projectDir}/reports"
  logs: "${projectDir}/logs"
  reads: "reads"
  reads_unzipped: "reads-unzipped"
  reads_trimmed: "reads-trimmed"
  reads_length: "150"
  glob: "*R{1,2}*.fastq.gz"
  glob_unzipped: "*R{1,2}*.fastq"
  genomes: "genomes"
  fungi: "ptr-m4"
  plant: "wheat-cs"
  adapters: "adapters.fasta"
  time: "time"
  fastp: "fastp"
  fastqc: "fastqc"
  star: "star"

files:
  conf: "conf"
  nf: "bin/nextflow"
  py3: "python3"
  config: "conf/generated/nextflow.conf"
  params: "conf/generated/params.yaml"
  common: "conf/common.toml"

workflow:
  skip_extract: "True"
  compress: "True"

nextflow:
  clean_logs: "True"
  resume: "True"

profile:
  active: "setonix"

