# Common data for pipeline
# Use quoted keys to avoid interpreting of keys

# Location of data, either relative to the "workflow.nf" script, as an
# absolute path, or prefixed with ${projectDir}
[data]
out = "${projectDir}/data"

reads = "${projectDir}/data/reads"
glob = "*R{1,2}*.fastq.gz"

time = "${projectDir}/data/time"
