# Configuration of Nextflow processes
#
# CPU values set to 0 are automatically set to the maximum available threads on
# the host system, set the value to number of threads
# Memory values set to 0 are automatically set to the maximum allocable memory
# on the host system, values set to -1 use memory allocation behaviour
# determined by the respective module, set the value to gigabytes (GB) of memory

[process]
executor = "local"

# Other pipeline configurations
[time]
bin = "/usr/bin/time"
flags = "-v"

[parallel]
bin = "parallel"
flags = ""


# Container engine parameters
[container]
# Container engine binary
# Default: ./
bin = "apptainer"

# Container engine options
# Default:
opts = ""

# Container runtime command
# Default: exec
exec = "exec"

# Options to append to the runtime command
# Default:
exec_opts = ""

# Enable the usage of a single container for the pipeline, see entry below to
# set path to the container.
# Default: true
monolithic = false

# Path to a container containing all binaries and tools used for the pipeline,
# only functional if monolithic is set to true, otherwise containers are loaded
# per-module.
# Default: NA
path = "${projectDir}/containers/comboseq"


# Module settings
[tools]
bc = "bc"
wc = "wc"


[extract]
# Resources
process = "local"
cores = 8
memory = 8

# Container options, corrects mismatched reads on alignment
container = false

# Command
bin = "pigz"
flags = ""


[samtools]
# Resources
cores = 4
memory = 8

# Container options
container = true
direct = false
path = ""

# Command
bin = "fastp"
flags = ""


[fastp]
# Resources
# Buffer is used for combining combining samples when using a batch allocator,
# currently not implemented
cores = 4
memory = -1
buffer = 4

# Container options
container = false
direct = false
path = "${projectDir}/containers/comboseq.sif"

# Command
bin = "fastp"
flags = ""


[star]
# Resources
# Memory allocation should be set to -1 to use the STAR module's automatic
# memory assignment
cores = 16
memory = 32

# Container options
container = true
path = "${projectDir}/containers/comboseq.sif"

# Command
bin = "STAR"
flags = ""


[trinity]
# Resources
cores = 16
memory = 48

# Container options
container = true
path = "${projectDir}/containers/trinity.sif"

# Command
bin = "Trinity"
flags = ""


[fastqc]
# Resources
cores = 1
memory = -1

# Container options
container = false
direct = false
path = "${projectDir/containers/comboseq.sif}"

# Command
bin = "fastqc"
flags = ""


[multiqc]
# Resources
cores = 1
memory = 1

# Container options
container = true
direct = false
path = "${projectDir/containers/comboseq.sif}"

# Command
bin = "multiqc"
flags = ""


[seqkit]
# Resources
cores = 1
memory = 1

# Container options
container = true
direct = false
path = "${projectDir}/containers/seqkit.sif"

# Command
bin = "seqkit"
flags = ""
