# Configuration of Nextflow processes
[process]
module = ["openjdk/17.0.0_35.lua"]
executor = "slurm"
clusterOptions = "--qos high"

# Location of binaries
[binaries.fastqc]
container = "${projectDir}/containers/container"
bin = "fastqc"
